services:
  db:
    container_name: portfolio-db
    image: postgres:15.1
    volumes:
      - portfolio-db:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

volumes:
  portfolio-db:
